### ISSUE TITLE
cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by jagtarsingh1232** [bradtraversy/devconnector_2.0#87] opened 2020-03-02 19:12 UTC
// @route  DELETE api/profile
// @desc  Delete api/profile, user & posts
// @access Private
router.delete('/', async (req, res) => {
  try {
    // @todo - remove users posts

    //@Remove profile

    await Profile.findOneAndRemove({ user: req.user.id });

    //@Remove user
    await User.findOneAndRemove({ _id: req.user.id });

    res.json({ msg: 'User deleted' });
  
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server Error');
  }
});
module.exports = router;

**Comment by bushblade** [comment] 2020-03-02 22:08
Hi there, can you explain how and where you get this error?
As of today I can successfully clone the repo, add a database and credentials and run the project with no errors.

**Comment by bushblade** [comment] 2020-03-03 15:24
Without any further information, I'll have to close this as an issue @jagtarsingh1232

**Comment by jagtarsingh1232** [comment] 2020-03-06 12:52
req.user.id -- is undefined can you explain something what i do wrong according to your with -any -expectations-you have

**Comment by bushblade** [comment] 2020-03-06 13:56
I'm afraid that is very vague.
Is this an issue with cloning this project or are you having problems with your own code?
If this is a issue with this repositories code then please explain the steps you take to reproduce this error, where you see the error (terminal or browser) and provide any error output. Also let us know your development enviroment.
If this is an issue with the Udemy course and your own project then please post in the course Q&A.

**Comment by bushblade** [comment] 2020-03-07 09:04
Due to lack of information and unable to replicate the issue with current code base, I'm closing this as an issue.

**Closed by bushblade** 2020-03-07 09:04 UTC
